### ISSUE TITLE
Expose MTU property on GATT characteristics

### ISSUE THREAD

**Issue by alexmoon** [bluez/bluer#103]
Would it be possible for bluer to make the MTU property available on `Characteristics`? I don't see a way currently to determine the maximum size of `value` that can be written as a single packet.

**Comment by surban** [comment]
Yes, this should be possible by exposing the [MTU](https://github.com/bluez/bluez/blob/df658c6c4ab5bd5ec4a8a3f8faa36e0d0a5f906a/doc/gatt-api.txt#L303) in https://github.com/bluez/bluer/blob/cfc9363160f1a66f312592ae96b5a746350e8f02/bluer/src/gatt/remote.rs#L204. 

Could you send me a pull request, when time permits?
