### ISSUE TITLE
LE Secure Connections

### ISSUE THREAD

**Issue by hvardhanx** [bluez/bluer#12]
Is there a way to do secure connections while pairing? Like this one: https://docs.rs/bluez/0.3.1/bluez/client/struct.BlueZClient.html#method.set_secure_connections_mode

**Comment by surban** [comment]
The function you mentioned is using the [Bluetooth Management API](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt) to directly reconfigure the Bluetooth adapter via a kernel interface.  Most functionality requires running as root.

The management API is currently not implemented in BlueR, instead it talks to `bluetoothd`  and relies on it to configure the adapter appropriately. At the moment `bluetoothd` does not expose functionality to reconfigure secure connections support.

I am not familiar with how `bluetoothd` handles LE secure connections, but it might that it is automatically configured according to the capabilities of the controller. You could ask in [their issue tracker](https://github.com/bluez/bluez/issues).

Generally, it would be interesting to have support for the management API in BlueR, but I never had the necessity to control the low-level settings of the adapter before.
