### ISSUE TITLE
Property events

### ISSUE THREAD

**Issue by jonasfoyth** [bluez/bluer#14]
Hello,

i'm using the latest version of bluer to get information from a ble device with sends periodic information by advertising. 

The property manufacture data is changing periodic, but the example "[discover devices](https://github.com/bluez/bluer/blob/master/bluer/examples/discover_devices.rs)" with option --changes is getting only RSSI events, not others.

Same using the function discover_devices_with_changes()...Only RSSI events...

This is an expected behavior?

**Comment by surban** [comment]
Should be fixed in 0.13.1.
