### ISSUE TITLE
Multi-central Nordic UART Service implementation

### ISSUE THREAD

**Issue by alexandrefresnais** [bluez/bluer#62]
Hello,

First, thanks for the amazing work!

I would like to know if it should be possible to implement the Nordic UART Service specification with this API ?

I know this question looks related to https://github.com/bluez/bluer/issues/58 but I cannot precisely see how it could be done in this specific case.

The Nordic documentation specifies that a central client may write on a RX Characteristic, and get answered with a notification.
As an example, I took a look at the `gatt_echo_server` and I could not see how I could echo the specific client which wrote me.

I understand that I can have multiple Write and Notify events, but I cannot see how I could link a writer and a notifier to answer the good client.

Is it possible ?

Thanks!

Regards,

Alexandre

**Comment by surban** [comment]
> I understand that I can have multiple Write and Notify events, but I cannot see how I could link a writer and a notifier to answer the good client.

I see your point. You would need to know the address of the client device to link the write and notify events.

It seems that the client device is indeed provided via the `device` property over D-Bus, see https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt#n105 for example, but BlueR is currently not exposing that property.

**Comment by surban** [comment]
Note that you will have to use IO-based notifications, because BlueZ does not provide the requesting device when using callback-based notifications. See https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt#n185

**Comment by surban** [comment]
> Wow, thank you very much. I will surely be taking a look at this with an iPhone in the following weeks. Would you be interested in a new example if I were making one ?

Yes, definitely!
