### ISSUE TITLE
Is this supposed to be private?

### ISSUE THREAD

**Issue by alxpettit** [bluez/bluer#90]
I can't use the AsyncRead or AsyncWrite traits for Stream, defined in `src/rfcomm/mod.rs`. The compiler says they're private. But how else am I supposed to write to a stream?

**Comment by surban** [comment]
There is no such thing as a private implementation of a public trait in Rust. `AsyncRead` and `AsyncWrite` are public, as you can see from the [docs](https://docs.rs/bluer/latest/bluer/rfcomm/struct.Stream.html#impl-AsyncRead-for-Stream).

**Comment by jmagnuson** [comment]
@alxpettit what is the error message from the compiler? Is the `rfcomm` [feature](https://github.com/bluez/bluer#crate-features) enabled?

**Comment by surban** [comment]
Closing, because no further information was provided. Feel free to re-open if the issue is not solved.
