### ISSUE TITLE
session.default_adapter().await? throws `Error: Error { kind: NotFound, message: "" }`

### ISSUE THREAD

**Issue by r-bt** [bluez/bluer#92]
bluer version: 0.16.0-pre1
bluez version: 5.68

I've got the following code:

```rust
let session = bluer::Session::new().await?;
let adapter = session.default_adapter().await?;
```

However, around every second time that I run it it throws `Error: Error { kind: NotFound, message: "" }`, I've added `println!` statements and identified that `let adapter = session.default_adapter().await?` is the cause.

**Comment by surban** [comment]
Could you verify that you have a working Bluetooth adapter using `bluetoothctl`?

**Comment by surban** [comment]
Closing, because no further information was provided. Feel free to re-open if the issue is not solved.
